version: '3.1' # specify docker-compose version
# Define the services/containers to be run
services:
 db:
    image: 'mysql/mysql-server:5.7'
    ports:
          - "3306:3306"
    environment:
          - MYSQL_DATABASE=don_du_sang
          - MYSQL_USER=root
          - MYSQL_PASSWORD=
           
    volumes:
          - ./my-datavolume:/var/lib/mysql
 backend:
    depends_on:
      - db
    build: DonDuSangBackend
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/don_du_sang?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : ,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    volumes:
     - .m2:/root/.m2
 angular:
   hostname: localhost
   #container_name: angular-app
   build: pfa-donDuSang
   ports:
     - 8181:80
   
 