pipeline {

    agent any
   // triggers {
     // cron('*/4 * * * *')

//    }

    stages {
    //   stage ('GIT') {
     //       steps {
      //         echo "Getting Project from Git";
       //        git branch:"master", url: 'https://github.com/dhouha16/SpringBootTest-CI.git';
       //     }
        //}

       stage("Verification du version Maven") {
           steps {
               dir('DonDuSangBackend') {
                bat "mvn -version"
               }
            }
        }
        stage("Supprimer le contenu du dossier target") {
                    steps {
                       
                            //this step attempts to clean the files and directories generated by Maven during its build
                        dir('DonDuSangBackend') {
                        bat 'mvn clean'
                        }
                        
                    }
                }
        stage ("Creation du livrable"){
        			steps{
                        dir('DonDuSangBackend') {
        				bat "mvn package -DskipTests=true"
                         }
        			}
//         			post {
//                     success {
//                        jacoco()
//                        junit '**/target/surefire-reports/TEST-*.xml'
//                     }
//                     }
        		}


        stage ("Lancement des Tests Unitaires"){
        		steps{
               dir('DonDuSangBackend') {
        			bat "mvn test"
               }
        				}
        		}

//         stage('Jacoco Test '){
//         			steps{
//         				step([$class: 'JacocoPublisher',
//               					execPattern: 'target/*.exec',
//               					classPattern: 'target/classes',
//               					sourcePattern: 'src/main/java',
//               					exclusionPattern: 'src/test*'
//         				])
//         			}
//         		}

        stage('Build pfa-donDuSang') {
            steps {
                dir('pfa-donDuSang') {
                    bat 'npm install -f'
                    bat 'npm run build'
                }
            }
            }
        
        stage('Deploy') {
      steps {
        dir('DonDuSangBackend') {
          bat 'docker build -t dhouha17/donfrontend .'
          bat 'docker run -d -p 8080:8080 dhouha17/donfrontend'
        }
        
        dir('DonDuSangBackend') {
          bat 'docker build -t dhouha17/donbackend .'
          bat 'docker run -d -p 80:80 dhouha17/donbackend'
        }
      }
    }

        stage("Analyse avec Sonar ") {
                	steps {
                     dir('DonDuSangBackend') {
                   	bat "mvn sonar:sonar -Dsonar.login=squ_db85c1e54c0b219a656e9a1bc387934b0c2517a6"
                     }
                	 }
               	}

        stage("Deploiement dans nexus ") {
                     steps{
                      // If you are using Windows then you should use "bat" step
                      // Since unit testing is out of the scope we skip them
                 dir('DonDuSangBackend') {
                bat "mvn deploy:deploy-file -DgroupId=com.pfa -DartifactId=don -Dversion=3.0 -DgeneratePom=true -Dpackaging=jar -DrepositoryId=deploymentRepo -Durl=http://localhost:8086/repository/maven-releases/ -Dfile=target/don-3.0.jar"
                        }
                     }
                }

    }


}